POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam jackson",
  "name": "Adam J",
  "password": "richAdam",
  "gender": "male",
  "location": "Detroit"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam jackson",
  "password": "richAdam"
}
###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard@123",
  "newPassword": "richard@123"
}


### 